name: Blog post workflow
on:
  schedule:
    # Runs every day at
    - cron: '0 21 * * *'

jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://zhtmr.github.io/feed.xml
          count: 6 # default 5
      - name: Commit file changes
        run: |
            git config --global user.name 'zhtmr'
            git config --global user.email '48509269+zhtmr@users.noreply.github.com'
            git add .
            git diff --quiet --cached || git commit -m "[auto] $(date -u +"%Y-%m-%d") Blog Posting List Update"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
